spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ben.c6wukdjxvf6m.ap-northeast-2.rds.amazonaws.com:3306/b
    username: s
    password: Q

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
